import {
  X,
  Check,
  ChevronsUpDown,
  PlusCircle,
  Store,
  Trash,
  Server,
  Copy,
  Plus,
  ImagePlus,
  MoreHorizontal,
  Edit,
  Search,
  ChevronRight,
  Circle,
  DollarSign,
  CreditCard,
  Package
} from "lucide-react"

export const Icons = {
  x: X,
  check: Check,
  chevronsUpDown: ChevronsUpDown,
  plusCircle: PlusCircle,
  store: Store,
  trash: Trash,
  server: Server,
  copy: Copy,
  plus: Plus,
  imagePlus: ImagePlus,
  moreHorizontal: MoreHorizontal,
  edit: Edit,
  search: Search,
  chevronRight: ChevronRight,
  circle: Circle,
  dollar: DollarSign,
  creditCard: CreditCard,
  package: Package
}
